import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";

export default defineConfig({
  extends: [core, react],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "**/android/**",
    "**/*.d.ts",
    "**/plugins/**/*.cjs",
  ],
  categories: {
    pedantic: "off",
  },
  rules: {
    "typescript/consistent-return": "off",
    "typescript/consistent-type-exports": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/promise-function-async": "off",
    "typescript/return-await": "off",
    "oxc/no-barrel-file": "off",
    "unicorn/filename-case": "off",
    "no-console": "off",
    "no-inline-comments": "off",
    "react-perf/jsx-no-new-function-as-prop": "off",
    "jest/require-hook": "off",
    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "no-duplicate-imports": "off",
    "max-lines": "off",
    "max-statements": "off",
    complexity: "off",
    "func-style": "off",
    "react/no-multi-comp": "off",
    "sort-keys": "off",
    "import/no-nodejs-modules": "off",
    "eslint/func-name-matching": "off",
    "eslint/logical-assignment-operators": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-empty-function": "off",
    "eslint/no-eq-null": "off",
    "eslint/no-negated-condition": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-plusplus": "off",
    "eslint/no-shadow": "off",
    "eslint/no-use-before-define": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/require-unicode-regexp": "off",
    "oxc/branches-sharing-code": "off",
    "promise/prefer-await-to-then": "off",
    "react/display-name": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/no-unstable-nested-components": "off",
    "react/react-compiler": "off",
    "typescript/method-signature-style": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-useless-switch-case": "off",
    "unicorn/prefer-dom-node-remove": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-ternary": "off",
  },
});
