CREATE TABLE photos (id INTEGER PRIMARY KEY AUTOINCREMENT, uri TEXT NOT NULL UNIQUE, width INTEGER NOT NULL, height INTEGER NOT NULL, captured INTEGER NOT NULL, size INTEGER NOT NULL, favorite INTEGER NOT NULL DEFAULT 0, original INTEGER NOT NULL DEFAULT 0, media_uri TEXT UNIQUE, pending INTEGER NOT NULL DEFAULT 0);
CREATE INDEX photos_order ON photos(captured DESC, id DESC);
